extends:
  - react-app
  - airbnb
  - airbnb/hooks
rules:
  max-len:
    - error
    - code: 115
      ignoreComments: true
      ignoreUrls: true
  object-curly-newline:
    - error
    - ObjectExpression:
        multiline: true
        consistent: true
      ObjectPattern:
        multiline: true
        consistent: true
  react/jsx-filename-extension: 'off'
  react/jsx-one-expression-per-line: 'off'
  jsx-a11y/label-has-associated-control: 'off'
  jsx-a11y/click-events-have-key-events: 'off'
  react/jsx-max-props-per-line:
    - error
    - maximum: 3
      when: multiline
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      newlines-between: always
settings:
  import/resolver:
    node:
      paths:
        - src
